# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'sandeepmkp'
    imageName: 'sandeepmkp.jfrog.io/mk-docker/node:16-alpine3.17'
    collectBuildInfo: true
    buildName: 'dockertestbuild'
    buildNumber: 'docker'
    module: 'node-16-alpine3.17'
    skipLogin: false

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'sandeepmkp-platform'
    command: |
      jf c add "dockertest" --artifactory-url="https://sandeepmkp.jfrog.io/artifactory" --interactive=false --user='manoj' --password=Password1* --basic-auth-only
      
      jf c use "dockertest"
      
      jf docker pull "sandeepmkp.jfrog.io/mk-docker/node:16-alpine3.17" --build-name="dockertestbuild" --build-number="docker" --module="node-16-alpine3.17" --server-id="dockertest"
