# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'mk-jfrog-artifactory-hts'
    sourceRepo: 'npmjs-remote'
    arguments: '--verbose'
    collectBuildInfo: true
    threads: '1'
    buildName: 'testnpm'
    buildNumber: '1'





