# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'maven-examples/maven-example/pom.xml'
    goals: 'deploy'
    artifactoryResolverService: 'mk-jfrog-artifactory-hts'
    targetResolveReleaseRepo: 'mk-libs-release'
    targetResolveSnapshotRepo: 'mk-libs-snapshot'
    artifactoryDeployService: 'mk-jfrog-artifactory-hts'
    targetDeployReleaseRepo: 'mk-libs-release'
    targetDeploySnapshotRepo: 'mk-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $JFROG_CLI_BUILD_NUMBER'
    
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'mk-jfrog-artifactory-hts'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'